force_keyboard_focus = true
hide_action_hints = true
autoplay_videos = true

[keybinds]
next = ["ctrl j"]
previous = ["ctrl k"]
quick_activate = []

[providers]
default = [
  "desktopapplications",
  "calc",
  "websearch",
  "bookmarks",
] # providers to be queried by default

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "."
provider = "clipboard"

[[providers.prefixes]]
prefix = "/"
provider = "files"
