#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]

prepend_keymap = [
  # misc
  { on = "t", run = "tab_create --current", desc = "Create a new tab with CWD" },
  { on = ["c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },

  # goto
  { on = [ "g", "h" ], run = "cd ~",            desc = "Go home" },
  { on = [ "g", "c" ], run = "cd ~/.config",    desc = "Go ~/.config" },
  { on = [ "g", "t" ], run = "cd /tmp",         desc = "Go /tmp" },
  { on = [ "g", "d" ], run = "cd ~/Downloads",  desc = "Go ~/Downloads" },
  { on = [ "g", "i" ], run = "cd ~/Pictures",   desc = "Go ~/Pictures" },
  { on = [ "g", "v" ], run = "cd ~/Videos",     desc = "Go ~/Videos" },
  { on = [ "g", "s" ], run = "cd ~/Documents",  desc = "Go ~/Documents" },
  { on = [ "g", "p" ], run = "cd ~/code",       desc = "Go ~/code" },
  { on = [ "g", "b" ], run = "cd ~/.local/bin", desc = "Go ~/.local/bin" },
]
